### ISSUE TITLE
Hook behavior on any item interaction

### ISSUE THREAD

**Issue by maxleiko** [acheronfail/istat#10]
## Feature request
I'd like to hook behavior on user interactions on items, say for starters, only `click` events.

Something like:
```toml
[[items]]
type = "disk"
interval = "10s"
mounts = ["/home"]
onclick = "i3-msg 'exec nemo /home'" # this is how I'd see it
```
or maybe
```toml
[[items]]
type = "disk"
interval = "10s"
mounts = ["/home"]
[actions]
click = "i3-msg 'exec nemo /home'" # this is how I'd see it
```

**Comment by acheronfail** [comment]
I've added this in [`fae19fb` (#11)](https://github.com/acheronfail/istat/pull/11/commits/fae19fb1c4414b2ef8704e3b0395aa48643ae820), which will appear in the next version.

I'll write some tests for it later and then once they're all good I'll create and release the next version.

You're welcome to checkout `next` though if you want to try it sooner.

**Comment by acheronfail** [comment]
@maxleiko I've merged in and bumped the version.

Check out the `sample_config.toml` file, when a command it run the item's properties are passed into it as environment variables, so things like `left_click = """ i3-msg exec "nemo $_mount_point" """` are possible. :slightly_smiling_face:

**Comment by maxleiko** [comment]
`left_click` works like a charm.

With modifiers I can't get it to work.

How do I get the `log.(info|debug)` to show (and where?) so that I can troubleshoot?

**Comment by acheronfail** [comment]
Hmm there are tests that verify the modifiers are working :thinking: and seems to work for me.

To get logs, you can run it like so

```
RUST_LOG=istat=trace istat 2>/tmp/istat
```

The values you can use as the modifiers are the same as `i3`, there's a list here: https://github.com/acheronfail/istat/blob/fc63f772c0bb6d4cf319d1cd5c463ecc0a03971e/src/i3/click.rs#L24-L32

Are you using the version that's currently on `master` now? There were a few tweaks before I merged.

**Comment by maxleiko** [comment]
This work no problem:
```toml
[items.actions]
left_click = "i3-msg exec pavucontrol"
```

This does not:
```toml
[items.actions]
left_click = { modifiers = ["Control"], command = "i3-msg exec pavucontrol" }
```

Might it be because of the `type = "pulse"` which is a "special" item with default actions (thinking about wheel events) ?

**Comment by acheronfail** [comment]
Hmm, that's quite strange - this is the configuration I have for my `pulse` item:

```toml
[[items]]
type = "pulse"
increment = 5
increment_sound = "~/.config/istat/volume.wav"
max_volume = 120
notify = "all"
[items.actions]
left_click = { modifiers = ["Control"], command = "i3-msg exec pavucontrol" }
```

and that works fine for me.

The `items.actions` hooks fire before the item even receives the click event, so it is the same for all items (the item itself can't override the behaviour).
